import { blankRecord, type Player, type WorldState } from "./model";

export const INVITATION_KEYS = ["shiroxler", "moji", "yasu", "hin"] as const;
export const invitationAvailable = (
  w: Pick<WorldState, "year" | "invitationComplete" | "invitationOffered">,
) => w.year === 2026 && w.invitationOffered === true && !w.invitationComplete;

/** One-time 2027 rookies, created only after the owner's two choices are confirmed. */
export function invitationCandidates(): Player[] {
  const specs = [
    {
      key: "shiroxler",
      name: "シロックスラー",
      position: "一",
      contact: 95,
      power: 30,
      speed: 30,
      catching: 30,
      arm: 30,
      fielding: 30,
      trajectory: 1,
    },
    {
      key: "moji",
      name: "湯上谷 モジ",
      position: "三",
      contact: 55,
      power: 95,
      speed: 45,
      catching: 65,
      arm: 55,
      fielding: 65,
      trajectory: 4,
    },
    {
      key: "yasu",
      name: "浜名 ヤス",
      position: "二",
      contact: 65,
      power: 65,
      speed: 65,
      catching: 75,
      arm: 75,
      fielding: 95,
      trajectory: 2,
    },
    {
      key: "hin",
      name: "坊西 ヒン",
      position: "捕",
      contact: 55,
      power: 55,
      speed: 55,
      catching: 85,
      arm: 85,
      fielding: 85,
      trajectory: 2,
    },
  ] as const;
  return specs.map((s) => ({
    id: "invite-" + s.key,
    invitationKey: s.key,
    name: s.name,
    species: "cat",
    breed: 0,
    age: 22,
    pro: 0,
    team: null,
    position: s.position,
    throws: "右",
    bats: "右",
    skills: {
      contact: s.contact,
      power: s.power,
      speed: s.speed,
      catching: s.catching,
      arm: s.arm,
      fielding: s.fielding,
      control: 30,
      stamina: 30,
    },
    velocity: 120,
    trajectory: s.trajectory,
    pitches: [],
    potential: 95,
    peak: 29,
    durability: 80,
    fatigue: 0,
    injured: 0,
    morale: 80,
    popularity: 80,
    trait: "特別招待選手",
    salary: 600,
    ask: 600,
    contractYear: 2027,
    market: "roster",
    registration: "senior",
    negotiation: "accepted",
    meetingReason: "",
    incentive: 0,
    promise: "none",
    draftYear: 2027,
    formerTeam: null,
    faRank: "C",
    reports: { 2026: blankRecord(2026, 0) },
    growth: [],
    scouting: 100,
    preference: "出場",
    offerRound: 0,
    offers: [],
  }));
}
